config/routes.rb
Rails.application.routes.draw do
  get 'results/show'
  root to: 'pages#home'
  devise_for :users
  resources :analyses, only: [ :index, :show, :new, :create ] do
    collection do
      post :upload, get: :new_csv
    end
  end
  resources :results do
    collection do
      get :download
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/analysis.rb
class Analysis < ApplicationRecord
  belongs_to :user
  has_many :results, dependent: :destroy
  validate :validate_keywords
  after_create_commit :scrape_keywords

  def keywords
    raw_keywords.split("\n").map(&:chomp)
  end

  private

  def validate_keywords
    keywords_count = keywords.count
    message = 'You must specificy between 1 and 100 keywords'
    errors.add :raw_keywords, message if keywords_count.zero? || keywords_count > 100
  end

  def scrape_keywords
    keywords.each_with_index do |keyword, index|
      SearchKeywordJob.perform_later id, keyword, index + 1
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :analysis
  validates :keyword, presence: true, uniqueness: { scope: :analysis }

  after_create :broadcast_result

  def broadcast_result
    ActionCable.server.broadcast("analysis_#{analysis.id}", {
      result_row: ApplicationController.renderer.render(
        partial: 'results/result',
        locals: { result: self }
      )
    })
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :analyses, dependent: :destroy
end

app/controllers/analyses_controller.rb
require 'csv'

class AnalysesController < ApplicationController
  def new
    @analysis = Analysis.new
  end

  def create
    @analysis = Analysis.new(analysis_params)
    save
  end

  def index
    @analyses = current_user.analyses
  end

  def show
    @analysis = Analysis.find(params[:id])
  end

  def upload
    keywords = ''
    keywords = CSV.read(analysis_params[:file].path).join("\n") if params[:analysis].present?
    @analysis = Analysis.new(raw_keywords: keywords)
    save
  end

  def save
    @analysis.user = current_user
    if @analysis.save
      redirect_to analysis_path(@analysis)
    else
      flash[:alert] = @analysis.errors[:raw_keywords][0]
      render :new
    end
  end

  private

  def analysis_params
    params.require(:analysis).permit(:raw_keywords, :file)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Localization
end

app/controllers/concerns/localization.rb
module Localization
  extend ActiveSupport::Concern

  included do
    before_action :set_locale

    protected

    def set_locale
      I18n.locale = params[:locale] || I18n.default_locale
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @analyses = Analysis.all
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def download
    @result = Result.find(params[:format])
    send_data @result.raw_html, filename: "#{@result.keyword}_raw_html.txt"
  end
end

app/helpers/analyses_helper.rb
module AnalysesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/analyses/create.html.erb
<h1>Analyses#create</h1>
<p>Find me in app/views/analyses/create.html.erb</p>

app/views/analyses/index.html.erb
<div class="container mb-5">
  <div class="d-flex justify-content-between align-items-center mt-5 mb-4">
    <h2 class="text-secondary">My analyses</h2>
    <%= button_to "New analysis", new_analysis_path, class: 'btn btn-outline-info', method: 'get' %>
  </div>
  <ul class="list-group">
    <% @analyses.each do |analysis| %>
      <%= link_to analysis_path(analysis), class: 'list-group-item list-group-item-action d-flex justify-content-between align-items-center' do %>
          Analysis #<%= analysis.id %>
          <div>
            <span class="font-italic">
              <%= time_ago_in_words(analysis.created_at) %> ago
            </span>
            <span class="badge badge-info badge-pill ml-2">
              <%= analysis.keywords.length %>
            </span>
          </div>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/analyses/new.html.erb
<div class="container">
  <h4 class="text-secondary pt-5">Select a method</h4>

  <h6 class="text-secondary pt-4">Enter a list of keywords</h6>

  <div class="form-group">
    <%= simple_form_for [@analysis] do |f| %>
      <%= f.text_area :raw_keywords, class: 'form-control', rows: 5 %>
      <%= f.submit class: 'form-control btn-outline-info mt-1' %>
    <% end %>
  </div>

  <h6 class="text-secondary pt-4">Upload a CSV file</h6>

  <div class="form-group">
    <%= simple_form_for [@analysis], url: upload_analyses_path do |f| %>
      <%= f.file_field :file, class: 'form-control-file' %>
      <%= f.submit class: 'form-control btn-outline-info mt-1' %>
    <% end %>
  </div>
</div>

app/views/analyses/show.html.erb
<div class="container">
  <h4 class="text-secondary pt-5">Analysis <%= @analysis.id %></h4>

  <table class="table mt-4">
    <thead class="thead-light">
      <tr>
        <th>Keyword</th>
        <th>Advertisers count</th>
        <th>Links count</th>
        <th>Search results</th>
        <th>HTML</th>
      </tr>
    </thead>
    <tbody id="keywords">
      <% @analysis.results.order(:position).each do |result| %>
        <%= render 'results/result', result: result %>
      <% end %>
    </tbody>
  </table>

  <script>
    App['analysis_<%= @analysis.id %>'] = App.cable.subscriptions.create(
      { channel: 'AnalysisChannel', analysis_id: <%= @analysis.id %> },
      {
        received: (data) => {
          document.getElementById('keywords').insertAdjacentHTML('beforeend', data.result_row);
        }
      }
    )
  </script>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='<%= I18n.locale %>'>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>Google Parser</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'i18n' %>
		<%= javascript_include_tag 'translations/translations' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="main-container">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<% if current_user %>
  <div class="container">
    <h4 class="text-secondary pt-5">Welcome <%= current_user.email %></h4>
    <p>
      You made <%= @analyses.count %> analyses so far.
      <% if @analyses.count > 0 %>
        <%= link_to 'See all analyses.', analyses_path %>
      <% else %>
        <%= link_to "It's time to create one!", new_analysis_path %>
      <% end %>
    </p>
    <div class="d-flex justify-content-center align-items-center text-center mt-5 pt-5">
      <div>
        <%= button_to "Start a new analysis", new_analysis_path, class: 'btn btn-outline-info btn-lg', method: 'get' %>
      </div>
    </div>
  </div>
<% else %>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1468070454955-c5b6932bd08d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1440&q=80);">
    <div class="container">
      <h1>Google parser</h1>
      <p>Extract data from the Google search results</p>
      <div>
      <%= button_to "Sign up now", new_user_registration_path, class: 'btn btn-info btn-lg', method: 'get' %>
    </div>
    </div>
  </div>
<% end %>

app/views/results/_result.html.erb
<tr>
  <td><strong><%= result.keyword %></strong></td>
  <td><%= result.adwords_advertiser_count %></td>
  <td><%= result.links_count %></td>
  <td><%= number_with_delimiter(result.results_count, :delimiter => '.') %></td>
  <td><%= link_to "Download", download_results_path(result.id) %></td>
</tr>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="flash flash-success alert alert-dismissible fade show" role="alert">
    <%= notice %>
    <a class="ml-5" data-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>
<% if alert %>
  <div class="flash flash-warning alert alert-dismissible fade show" role="alert">
    <%= alert %>
    <a class="ml-5" data-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-custom">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%#= image_tag "" %>
    Google parser
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active mr-3">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item active mr-3">
          <%= link_to "Analyses", analyses_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://miamivalleycap.org/wp-content/uploads/2017/01/placeholder-person.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>